org:
  hibernate:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false
    user: root
    password:
    dialect: org.hibernate.dialect.MySQLDialect



springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
